version: '3.6'
services:
  php-fpm:
    build: .
    volumes: 
      - ./src:/data/www:rw
    links: 
      - db:db
    restart: always
  nginx:
    build: ./Nginx
    depends_on: 
      - phpmyadmin
      - php-fpm
    links: 
      - php-fpm:php-fpm
      - phpmyadmin:phpmyadmin
    volumes: 
      - ./Nginx/logs:/etc/nginx/logs:rw
      - ./Nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ./Nginx/conf/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./src:/data/www:rw
    ports: 
      - "8081:80"
      # - "443:443"
    command: nginx -g 'daemon off;'
  db:
    build: ./MySQL
    # ports: 
    #   - "4000:3306"
    volumes:
      - ./MySQL/data:/var/lib/mysql:rw
      - ./MySQL/logs:/var/lib/mysql-logs:rw
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    command: "--character-set-server=utf8"
  phpmyadmin:
    build: ./phpMyAdmin
    ports: 
      - "8082:80"
    links: 
      - db:db
    depends_on: 
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
